registreerocks/registree-core

src/queries/queries.service.ts

When setting the RSVP status for a student on an invite, set the invite to viewed if not viewed already to prevent bad state.
Task #311

When setting the RSVP status for a student on an invite, set the invite to viewed

---

src/queries/queries.service.ts
src/queries/resolvers/event-details.resolver.ts

The first call sets the attended to true when the linking happens, so no need for the second call.
see:
https://github.com/registreerocks/query-db-api/blob/389701a84b541308b58c3fe42d6ec47f90f0a5dd/package/src/swagger_server/controllers/update.py#L6-L13

fix(#326): remove redundant update invite call

---

test/app.e2e-spec.ts
test/jest-e2e.json

This makes `yarn test:e2e` work again.
(I know we only have the "Hello, world!" E2E test, but that's still useful for integration smoke-testing, and as a foundation for future tests.)

Fix E2E test

---

.circleci/config.yml

This mainly fixes the package caching to work for Yarn 2, ut also cleans up the CircleCI build steps a bit (see commits and comments).
This is really something that should be fixed in the upstream `circleci/node` orb: I'll file an issue for it.
```
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 7 packages were already cached, 1465 had to be fetched
➤ YN0000: └ Completed in 1m 16s
```
````
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 1465 packages were already cached
➤ YN0000: └ Completed in 0s 492ms
````
🎉

CI: fix Yarn 2 caching

---

.circleci/config.yml
.env.tests

(Closes #353)
This adds a very straightforward `test-e2e` job alongside the existing `test` job. This doesn't really add any intentional test coverage, on its own, but at least it serves as a simple integration smoke-test, and as a base to work on.

CI: add test-e2e job

---

.eslintrc.js
package.json
src/common/test.helpers.spec.ts
src/common/test.helpers.ts
yarn.lock

Blocks #363
This adds two test helpers split out from the work in #363:
* `coerceNullPrototypeObjects`
* `execGraphQL`
The implementations are finicky, so these come with tests themselves, but they should allow writing simpler and better GraphQL tests in general.

test: helpers for GraphQL

---

.github/dependabot.yml

Upstream issue:
https://github.com/dependabot/dependabot-core/issues/1297

chore(dependabot): disable npm ecosystem for now, pending Yarn 2 support

---

package.json
src/common/amount.union.regression.spec.ts
src/common/amount.union.ts
yarn.lock

This adds a regression test and workaround for the @nestjs/graphql bug.
Closes #367

fix: GraphQL union type resolving

---

package.json
test/jest-e2e.json
tsconfig.json
yarn.lock

1. Use Yarn 2 link protocol for `src` package. This simplifies module name resolution situation a bit, and removes the need for **moduleNameMapper** in the Jest configs. ([Yarn 2 docs](https://yarnpkg.com/features/protocols#why-is-the-link-protocol-recommended-over-aliases-for-path-mapping))
2. Add missing Jest **testRegex** escapes for `.`. Without this, the base Jest config's pattern (`.spec.ts$`) matches `*.e2e-spec.ts` too.
3. Remove tsconfig **baseUrl** (no longer needed).
4. Change Jest **rootDir** from `src` to `.`, and add `test` as **root**. This allows Jest to find non-E2E tests under the `test` directory too.
(I pulled these changes and fixes out of the work in progress for #363: they're general maintenance that's easier to review separately.)

Refactor module import config

---

src/common/amount.union.regression.spec.ts
src/queries/dto/create-event-query.input.arb.ts
src/queries/dto/create-event-query.input.spec.ts
src/queries/dto/create-event-query.input.ts
src/queries/dto/expand-event-query.input.arb.ts
src/queries/dto/expand-event-query.input.spec.ts
src/queries/dto/expand-event-query.input.ts
src/queries/mappers/map-query-details.ts
src/queries/models/academic-year-of-study.model.ts
src/queries/models/query-details.model.ts
src/queries/queries.module.ts
src/queries/resolvers/__snapshots__/event-queries.resolver.spec.ts.snap
src/queries/resolvers/academic-year-of-study.resolver.spec.ts
src/queries/resolvers/academic-year-of-study.resolver.ts
src/queries/resolvers/event-queries.resolver.spec.ts
src/schema.graphql
test/queries.e2e-spec.ts

Closes #355
Tasks from issue:
Deferred:
- ~For `expandQuery` buckets can only be added, and never be removed~ (deferred until we implement the real functionality)

feat: add Academic Year of Study

---

yarn.lock

This is a security update for CVE-2021-27290, Regular Expression Denial of Service (ReDoS):
> ssri 5.2.2-8.0.0, fixed in 8.0.1, processes SRIs using a regular
expression which is vulnerable to a denial of service. Malicious SRIs
could take an extremely long time to process, leading to denial of
service. This issue only affects consumers using the strict option.
* https://github.com/advisories/GHSA-vx3p-948g-6vhq

chore(deps): update ssri 8.0.0 → 8.0.1

---

yarn.lock

This fixes CVE-2020-7774 (Prototype Pollution):
* https://github.com/advisories/GHSA-c4w7-xm78-47vh
* https://nvd.nist.gov/vuln/detail/CVE-2020-7774

chore(deps): security update y18n 4.0.0 → 4.0.1

---

package.json
yarn.lock

This fixes a DoS vulnerability:
* https://github.com/advisories/GHSA-6fc8-4gx4-v693
* https://nvd.nist.gov/vuln/detail/CVE-2021-32640

chore(deps): security update ws → ^7.4.6 (CVE-2021-32640)

---

package.json
yarn.lock

This should be low-impact for us, but still:
* https://github.com/advisories/GHSA-7p7h-4mm5-852v
* https://nvd.nist.gov/vuln/detail/CVE-2021-33623

chore(deps): update commitlint 11 → 12, for trim-newlines security advisory

---

yarn.lock

Fixes:
* https://github.com/advisories/GHSA-ww39-953v-wcq6
* https://nvd.nist.gov/vuln/detail/CVE-2020-28469
* https://github.com/gulpjs/glob-parent/pull/36

chore(deps): security update glob-parent 5.1.1 → 5.1.2

---

yarn.lock

This fixes two vulnerabilities:
CVE-2021-32803 (CVSS 8.2 High, Arbitrary File Creation/Overwrite via
insufficient symlink protection due to directory cache poisoning):
* https://github.com/advisories/GHSA-r628-mhmh-qjhw
* https://nvd.nist.gov/vuln/detail/CVE-2021-32803
CVE-2021-32804 (CVSS 8.2 High, Arbitrary File Creation/Overwrite due to
insufficient absolute path sanitization):
* https://github.com/advisories/GHSA-3jfq-g458-7qm9
* https://nvd.nist.gov/vuln/detail/CVE-2021-32804

chore(deps): security update tar 6.0.5 → 6.1.6 (CVSS 8.2 High)

---

yarn.lock

This fixes:
* CVE-2021-37701, https://github.com/advisories/GHSA-9r2w-394v-53qc
* CVE-2021-37712, https://github.com/advisories/GHSA-qq89-hq3f-393p
* CVE-2021-37713, https://github.com/advisories/GHSA-5955-9wpr-37jh

chore(deps): security update tar 6.1.6 → 6.1.11

---

yarn.lock

This fixes:
* CVE-2021-3749, https://github.com/advisories/GHSA-cph5-m8f7-6c5x

chore(deps): security update axios 0.21.1 → 0.21.4

---

yarn.lock

This fixes:
* CVE-2021-23434, https://github.com/advisories/GHSA-v39p-96qg-c8rf

chore(deps): security update object-path 0.11.4 → 0.11.7

---

.circleci/config.yml

- fix Node versions to 16 (LTS), rather than 17
- update circleci/node orb, and use new yarn-berry support

ci: use Node 16 LTS for CirceCI, and Yarn 2 updates
