registreerocks/registree-core

src/common/pagination/pagination.ts, src/queries/queries.service.ts, src/queries/resolvers/event-queries.resolver.ts, src/query-data/dto/attachment.dto.ts, src/query-data/dto/create-query.request.ts, src/query-data/dto/event.response.ts
Fix #67 - Renamed Cursor to Connection in pagination.ts
Fix #68 - Removed unused DI in event queries
Fix #70 - Use DTO for commonly used type
=> Clean up some misc issues

src/queries/queries.service.ts, src/queries/resolvers/event-queries.resolver.ts, src/schema.graphql, yarn.lock
Sorry for the commit mess. A lot of merge and rebase conflicts. Never branch off of master :-/
Resolve #14
=> Feat: query event query by id

src/queries/dto/create-event-query.input.ts, src/queries/mappers/mapEventDetails.ts, src/queries/models/event-details.model.ts, src/queries/queries.service.ts, src/query-data/dto/create-query.request.ts, src/query-data/dto/event.response.ts, src/schema.graphql
=> feat: add (call) password to event details

src/queries/queries.service.ts
=> feat: default sorting of queries

src/constants.ts, src/queries/queries.service.ts
=> feat: file type restriction on upload

src/app.module.ts, src/constants.ts, src/queries/queries.service.ts
=> feat: file size restriction

src/queries/models/event-query.model.ts, src/queries/queries.service.ts, src/queries/resolvers/event-queries.resolver.ts, src/schema.graphql
=> Sb eventquery plus pricing

src/queries/mappers/map-query-details.ts, src/queries/models/pagination/query-transcript-connection.model.ts, src/queries/models/query-details.model.ts, src/queries/queries.module.ts, src/queries/resolvers/query-details.resolver.ts, src/schema.graphql
=> feat: added pagination for query results

src/app.module.ts, src/auth/jwt.strategy.ts, src/auth0-data/dto/create-user.response.ts, src/auth0-data/dto/get-user.response.ts, src/auth0-data/dto/update-user.response.ts, src/common/interfaces/user.interface.ts, src/customers/models/customer.model.ts, src/schema.graphql, src/students/models/student.model.ts, src/students/students.module.ts, src/students/students.resolver.ts, src/students/students.service.ts, src/users/models/contact.model.ts, src/users/users.resolver.ts, src/users/users.service.ts
=> Feat: view student user details

src/all-exceptions.filter.ts, src/app-config/app-config.service.ts, src/app.module.ts, src/common/errors/argument-validation.error.ts, src/customers/customers.resolver.ts, src/customers/customers.service.ts, src/customers/dto/update-billing-details.input.ts, src/customers/dto/update-customer-details.input.ts, src/customers/models/customer.model.ts, src/main.ts, src/rules.ts, src/schema.graphql
=> feat: added update customer mutations

src/queries/dto/create-event-query.input.ts, src/queries/models/event-details.model.ts, src/query-data/dto/create-query.request.ts, src/schema.graphql
=> fix: make password nullable on event details

src/auth0-data/auth0-data.service.ts, src/contacts/contacts.service.ts, src/contacts/mappers/map-contact.ts, src/customers/customers.resolver.spec.ts, src/customers/customers.resolver.ts, src/customers/customers.service.ts, src/customers/models/customer.model.ts, src/schema.graphql
I think we have to flush core db in order to make this work since I changed the schema.
=> feat: return auth0 user when customer contacts are queried

src/linking-data/linking-data.service.ts, src/queries/queries.service.ts
Reverts registreerocks/registree-core#306
=> Revert "feat: remove url from linking data call"

src/customers/customers.module.ts, src/customers/customers.service.ts, src/customers/loaders/customers.loader.ts, src/queries/resolvers/event-queries.resolver.ts
=> feat: use dataloader for customer's field resolver

src/customers/customers.controller.ts
endpoints needed for admin notebooks
=> feat: get one or all customers (for notebooks)

src/auth/current-user.decorator.ts, src/common/graphql.helpers.spec.ts, src/common/graphql.helpers.ts, src/rules.spec.ts, src/rules.ts
=> Fix user scope rules

.circleci/config.yml, .github/dependabot.yml, package.json, src/upload/upload.module.ts, tsconfig.json
* Apply `prettier` to files that were missed
* Add YAML to `husky`'s pre-commit file extension list
=> Style: format straggler files with prettier

src/app.module.ts, src/schema.graphql
This keeps the file in a durable order, so that it doesn't change depending on the order that modules get loaded.
=> chore: enable GraphQLModule's sortSchema for schema.graphql

src/queries/dto/create-event-query.input.arb.ts, src/queries/dto/create-event-query.input.spec.ts, src/queries/dto/create-event-query.input.ts, src/queries/dto/degree.input.arb.ts, src/queries/dto/degree.input.spec.ts, src/queries/dto/degree.input.ts
This is a byproduct of #363, but it's fairly stand-alone fix, so I'm splitting it out for easier review.
=> fix(queries): CreateEventQueryInput validation

yarn.lock
Type: CWE-1333: Inefficient Regular Expression Complexity
CVSS Score: 5.3 Moderate
* https://github.com/advisories/GHSA-qgmg-gppg-76g5
* https://nvd.nist.gov/vuln/detail/CVE-2021-3765
=> fix(deps): security update validator 13.5.2 → 13.7.0

src/common/amount.union.regression.spec.ts, src/queries/dto/create-event-query.input.ts, src/queries/mappers/map-query-details.ts, src/queries/models/query-details.model.ts, src/queries/queries.service.ts, src/queries/resolvers/__snapshots__/event-queries.resolver.spec.ts.snap, src/query-data/dto/create-query.request.ts, src/query-data/dto/query.response.ts, src/schema.graphql
WIP since it is based off of the average queries branch for now
=> feat: add race and gender demographics support for queries

src/queries/mappers/map-event-summary.ts, src/queries/models/event-summary.model.ts, src/queries/queries.service.ts, src/queries/resolvers/__snapshots__/event-queries.resolver.spec.ts.snap, src/queries/resolvers/event-queries.resolver.ts, src/schema.graphql
=> feat(query): add event summary query
